apiVersion: v1
kind: Service
metadata:
  name: neo4j
  labels:
    run: neo4j
spec:
  ports:
  - port: 7474
    targetPort: 7474
    protocol: TCP
  selector:
    app: neo4j
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: neo4j-deployment
  labels:
    app: neo4j
spec:
  replicas: 1
  selector:
    matchLabels:
      app: neo4j
  template:
    metadata:
      labels:
        app: neo4j
    spec:
      containers:
      - name: neo4j
        image: neo4j
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 7474