apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    -  host: nginx.example.local
       http:
        paths:
        - path: /orders
          backend:
            serviceName: orders-service-svc
            servicePort: 80
